export enum Err {
	FailedExecute = "Unable to execute command",
	FailedSave = "Failed saving command data",
	InvalidAuthorLength = "Invalid author length ([max 256 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidChannelId = "Channel does not exist",
	InvalidChannelType = "Invalid channel type",
	InvalidDescriptionLength = "Invalid description length ([max 4096 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidFieldCount = "Invalid field count ([max 25 fields](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidFieldTitleLength = "Invalid field title length ([max 256 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidFieldValueLength = "Invalid field value length ([max 1024 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidFooterLength = "Invalid footer length ([max 2048 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidGuildId = "Guild does not exist",
	InvalidLabelLength = "Invalid label length ([max 45 characters](https://discord.com/developers/docs/interactions/message-components#text-inputs-text-input-structure))",
	InvalidMessageId = "Message does not exist",
	InvalidPermissions = "Invalid permission level",
	InvalidRoleId = "Role does not exist",
	InvalidTitleLength = "Invalid title length ([max 256 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits))",
	InvalidUserId = "User does not exist",
	MissingChannel = "Must be used within a channel",
	MissingGuild = "Must be used within a guild",
	MissingIdData = "Missing interaction payload data (tell Jaxydog#6422)",
	MissingMessage = "Must be used triggered from a message",
	MissingTextChannel = "Must be used within a text channel",
}
export module Err {
	export enum Apply {
		ExpectedPendingStatus = "Application is not pending",
		FailedAbout = "Error occurred while creating about embed",
		FailedAccept = "Error occurred while accepting form",
		FailedDeny = "Error occurred while denying form",
		FailedOutput = "Error occurred while sending application to moderators",
		FailedResubmit = "Error occurred while requesting resubmit",
		FailedSubmit = "Error occurred while submitting application",
		MissingConfig = "Applications have not been configured",
		MissingResponse = "Unable to find user application",
		MissingTimezones = "No timezone data is stored",
		UnexpectedResponse = "There is already an existing application",
	}
	export enum Poll {
		FailedSubmit = "Error occurred while responding to poll",
		InvalidChoiceCount = "Maximum of 10 choices permitted",
		InvalidDescriptionLength = "Poll description must be at most 2048 characters",
		InvalidDuration = "Poll duration must be greater than 0 hours and at most 72 hours",
		InvalidUser = "Poll authors cannot vote on their own polls",
		MissingChoice = "Choice does not exist",
		MissingChoices = "Poll must have at least 2 choices",
		MissingClosesUnix = "Poll is missing duration data",
		MissingConfig = "Polls have not been configured",
		MissingOutputMessage = "The poll has not been posted",
		MissingPoll = "A poll has not been created",
		UnexpectedChoice = "Choice has already been added",
		UnexpectedOutputMessageDelete = "Sent polls cannot be deleted",
		UnexpectedOutputMessageSend = "The poll has already been sent",
		UnexpectedPoll = "A poll already exists",
		UnexpectedResponse = "A response has already been submitted",
		UnexpectedResponseClosed = "Unable to respond to a closed poll",
	}
	export enum Role {
		FailedSelector = "Error occurred while selecting role",
		MissingRole = "Role selector does not exist",
		UnexpectedRole = "Role has already been added",
	}
	export enum Mail {
		FailedAbout = "Error occurred while creating about embed",
		FailedArchive = "Error occurred while archiving channel",
		FailedCreate = "Error occurred while creating ModMail channel",
		FailedInfo = "Error occurred while changing archive previews",
		FailedView = "Error occurred while viewing archive",
		InvalidCategory = "Invalid category channel",
		InvalidStatus = "You must be a member of this guild to use ModMail",
		MissingArchive = "Archive does not exist",
		MissingArchives = "There are no archived ModMail channels",
		MissingConfig = "Modmail has not been configured",
		UnexpectedChannel = "There is already an active ModMail channel",
	}
	export enum Star {
		InvalidChannelId = "Star channel does not exist",
		UnexpectedChannel = "Star channel output cannot be the same as input",
	}
}
